export const TEMP_VALLUES = {
    HOME: {
        LONG_TEXT: 'Рождение кожаного изделия начинается в тишине мастерской, где время течет не минутами, а движениями. Это не производство — это медленный диалог между руками мастера и памятью материала, который когда-то дышал. Пальцы читают историю, записанную в зернистой текстуре: где кожа упруга, где мягка, где несет на себе шрам от прежней жизни. Эти следы не скрывают — их вписывают в замысел, превращая в уникальную подпись природы. Совершенство здесь — не в безупречной гладкости, а в подлинности. Затем начинается танец инструментов. Нож режет с уважением, одним уверенным движением. Игла рождает шов — стежок за стежком, ровно и плотно, как слова в хорошем предложении. Это медитация в движении, где каждый этап — обязательная нота: вырезать, обработать, собрать, прошить. Здесь нет места спешке, только терпеливая последовательность.',
        ZAGOL: 'Искусство кожи: тихая бесконечность в ладонях мастера'
    },
    ABOUTME:{
        ZAGOL: 'Меня зовут Имярек',
        LONG_TEXT_1: '. . .и вот уже пятнадцать лет мои руки помнят запах кожи — терпкий, глубокий, живой. Это не просто материал. Это история, пойманная в ладони. Мое ремесло началось не в мастерской, а в детстве, с отцовского старого ремня, потёртого до благородного блеска. Я тогда думал: как так получается, что вещь, которую носят годами, становится только красивее? Ответ пришёл позже, с первым куском дублёной кожи, первым шилом, первой нитью, продетой в иглу с тупыми, натруженными пальцами. Я не штампую изделия. Я беседую с кожей. У каждого среза — свой характер. Где-то она упряма и плотна, где-то — мягка и податлива. Задача мастера — не сломать этот нрав, а понять его и помочь проявиться. Нож скользит не по шаблону, а вдоль естественной линии; строчка ложится не для вида, а чтобы на века; края шлифуются до бархатистости, которую хочется трогать снова и снова.',
        LONG_TEXT_2: 'Я делаю вещи, которые переживут моду. Кошелёк, который станет только мягче и благороднее от монет и воспоминаний. Ремень, который будет обнимать талию десятилетиями. Сумку, на которой появятся царапины от ключей, следы от дождя, отпечаток вашей жизни. В этом и есть магия: я даю вещам начало, а вы даёте им душу. Моя мастерская — это место тишины, стука молотка, запаха воска и кофе. Здесь нет конвейера. Есть верстак, залитый светом, набор инструментов, отточенных до блеска, и тихое удовлетворение от того, что в мире, который летит куда-то в цифровую даль, ты создаёшь что-то простое, осязаемое и настоящее. Что-то, что будет согревать руки и хранить то, что важно. Приходите. Потрогайте кожу. Услышьте её шепот. И, возможно, найдёте здесь ту самую вещь, которая будет ждать вас утром на стуле, став не просто аксессуаром, а молчаливым спутником ваших дней.'
    },
    SERVICE:{
        ZAGOL:'Тут будет много текста о правильном уходе за кожей',
        LONG_TEXT_1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In consectetur sit amet ex nec aliquet. Duis vulputate ante eget maximus eleifend. Cras sed augue sed odio consectetur hendrerit. Nulla vitae gravida lorem, non tristique orci. Aliquam non porttitor mi, at lobortis erat. Aenean eu nulla eget sapien dictum scelerisque. Aenean vel felis eleifend, viverra velit ultrices, scelerisque nibh. Nulla varius libero id dapibus lobortis.\n' +
            '\n' +
            'Aliquam erat volutpat. Vestibulum fringilla nec sem euismod suscipit. Morbi aliquam, mauris in mattis pharetra, orci velit hendrerit lectus, ac commodo leo libero quis risus. Phasellus cursus sed felis vel pulvinar. In ultrices nulla diam, at mollis ligula pulvinar quis. Vestibulum sit amet tortor dictum neque tempus scelerisque. Pellentesque placerat, ligula varius placerat sagittis, leo ex vestibulum diam, quis consectetur augue sapien eget nunc. Aliquam ac metus dolor.',
        LONG_TEXT_2: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In consectetur sit amet ex nec aliquet. Duis vulputate ante eget maximus eleifend. Cras sed augue sed odio consectetur hendrerit. Nulla vitae gravida lorem, non tristique orci. Aliquam non porttitor mi, at lobortis erat. Aenean eu nulla eget sapien dictum scelerisque. Aenean vel felis eleifend, viverra velit ultrices, scelerisque nibh. Nulla varius libero id dapibus lobortis.\n' +
            '\n' +
            'Aliquam erat volutpat. Vestibulum fringilla nec sem euismod suscipit. Morbi aliquam, mauris in mattis pharetra, orci velit hendrerit lectus, ac commodo leo libero quis risus. Phasellus cursus sed felis vel pulvinar. In ultrices nulla diam, at mollis ligula pulvinar quis. Vestibulum sit amet tortor dictum neque tempus scelerisque. Pellentesque placerat, ligula varius placerat sagittis, leo ex vestibulum diam, quis consectetur augue sapien eget nunc. Aliquam ac metus dolor.',
    },
    FABRICATION: {
        ZAGOL:'Вот несколько примеров изготовления'
    }

};
